apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-microservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quarkus-microservice
  template:
    metadata:
      labels:
        app: quarkus-microservice
    spec:
      containers:
        - name: quarkus-microservice
          image: quarkus/quarkus-microservice
          imagePullPolicy: Never
          ports:
            - name: quarkus-port
              containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: quarkus-microservice-service
spec:
  ports:
    - port: 80
      targetPort: quarkus-port
      protocol: TCP
  selector:
    app: quarkus-microservice
  type: LoadBalancer
